/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContestCodeRouteRouteImport } from './routes/$contestCode/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ContestCodeIndexRouteImport } from './routes/$contestCode/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminContestsCreateRouteImport } from './routes/admin/contests/create'
import { Route as ContestCodeProblemProblemIdRouteImport } from './routes/$contestCode/problem/$problemId'
import { Route as AdminContestsContestIdIndexRouteImport } from './routes/admin/contests/$contestId/index'
import { Route as AdminContestsContestIdEditRouteImport } from './routes/admin/contests/$contestId/edit'
import { Route as AdminContestsContestIdProblemsCreateRouteImport } from './routes/admin/contests/$contestId/problems/create'
import { Route as AdminContestsContestIdProblemsProblemIdEditRouteImport } from './routes/admin/contests/$contestId/problems/$problemId/edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestCodeRouteRoute = ContestCodeRouteRouteImport.update({
  id: '/$contestCode',
  path: '/$contestCode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ContestCodeIndexRoute = ContestCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContestCodeRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContestsCreateRoute = AdminContestsCreateRouteImport.update({
  id: '/contests/create',
  path: '/contests/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ContestCodeProblemProblemIdRoute =
  ContestCodeProblemProblemIdRouteImport.update({
    id: '/problem/$problemId',
    path: '/problem/$problemId',
    getParentRoute: () => ContestCodeRouteRoute,
  } as any)
const AdminContestsContestIdIndexRoute =
  AdminContestsContestIdIndexRouteImport.update({
    id: '/contests/$contestId/',
    path: '/contests/$contestId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminContestsContestIdEditRoute =
  AdminContestsContestIdEditRouteImport.update({
    id: '/contests/$contestId/edit',
    path: '/contests/$contestId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminContestsContestIdProblemsCreateRoute =
  AdminContestsContestIdProblemsCreateRouteImport.update({
    id: '/contests/$contestId/problems/create',
    path: '/contests/$contestId/problems/create',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminContestsContestIdProblemsProblemIdEditRoute =
  AdminContestsContestIdProblemsProblemIdEditRouteImport.update({
    id: '/contests/$contestId/problems/$problemId/edit',
    path: '/contests/$contestId/problems/$problemId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$contestCode': typeof ContestCodeRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/$contestCode/': typeof ContestCodeIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$contestCode/problem/$problemId': typeof ContestCodeProblemProblemIdRoute
  '/admin/contests/create': typeof AdminContestsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/contests/$contestId/edit': typeof AdminContestsContestIdEditRoute
  '/admin/contests/$contestId/': typeof AdminContestsContestIdIndexRoute
  '/admin/contests/$contestId/problems/create': typeof AdminContestsContestIdProblemsCreateRoute
  '/admin/contests/$contestId/problems/$problemId/edit': typeof AdminContestsContestIdProblemsProblemIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/$contestCode': typeof ContestCodeIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$contestCode/problem/$problemId': typeof ContestCodeProblemProblemIdRoute
  '/admin/contests/create': typeof AdminContestsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/contests/$contestId/edit': typeof AdminContestsContestIdEditRoute
  '/admin/contests/$contestId': typeof AdminContestsContestIdIndexRoute
  '/admin/contests/$contestId/problems/create': typeof AdminContestsContestIdProblemsCreateRoute
  '/admin/contests/$contestId/problems/$problemId/edit': typeof AdminContestsContestIdProblemsProblemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$contestCode': typeof ContestCodeRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/$contestCode/': typeof ContestCodeIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$contestCode/problem/$problemId': typeof ContestCodeProblemProblemIdRoute
  '/admin/contests/create': typeof AdminContestsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/contests/$contestId/edit': typeof AdminContestsContestIdEditRoute
  '/admin/contests/$contestId/': typeof AdminContestsContestIdIndexRoute
  '/admin/contests/$contestId/problems/create': typeof AdminContestsContestIdProblemsCreateRoute
  '/admin/contests/$contestId/problems/$problemId/edit': typeof AdminContestsContestIdProblemsProblemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$contestCode'
    | '/admin'
    | '/about'
    | '/admin/login'
    | '/$contestCode/'
    | '/admin/'
    | '/$contestCode/problem/$problemId'
    | '/admin/contests/create'
    | '/api/auth/$'
    | '/admin/contests/$contestId/edit'
    | '/admin/contests/$contestId/'
    | '/admin/contests/$contestId/problems/create'
    | '/admin/contests/$contestId/problems/$problemId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/login'
    | '/$contestCode'
    | '/admin'
    | '/$contestCode/problem/$problemId'
    | '/admin/contests/create'
    | '/api/auth/$'
    | '/admin/contests/$contestId/edit'
    | '/admin/contests/$contestId'
    | '/admin/contests/$contestId/problems/create'
    | '/admin/contests/$contestId/problems/$problemId/edit'
  id:
    | '__root__'
    | '/'
    | '/$contestCode'
    | '/admin'
    | '/about'
    | '/admin/login'
    | '/$contestCode/'
    | '/admin/'
    | '/$contestCode/problem/$problemId'
    | '/admin/contests/create'
    | '/api/auth/$'
    | '/admin/contests/$contestId/edit'
    | '/admin/contests/$contestId/'
    | '/admin/contests/$contestId/problems/create'
    | '/admin/contests/$contestId/problems/$problemId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContestCodeRouteRoute: typeof ContestCodeRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$contestCode': {
      id: '/$contestCode'
      path: '/$contestCode'
      fullPath: '/$contestCode'
      preLoaderRoute: typeof ContestCodeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$contestCode/': {
      id: '/$contestCode/'
      path: '/'
      fullPath: '/$contestCode/'
      preLoaderRoute: typeof ContestCodeIndexRouteImport
      parentRoute: typeof ContestCodeRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contests/create': {
      id: '/admin/contests/create'
      path: '/contests/create'
      fullPath: '/admin/contests/create'
      preLoaderRoute: typeof AdminContestsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$contestCode/problem/$problemId': {
      id: '/$contestCode/problem/$problemId'
      path: '/problem/$problemId'
      fullPath: '/$contestCode/problem/$problemId'
      preLoaderRoute: typeof ContestCodeProblemProblemIdRouteImport
      parentRoute: typeof ContestCodeRouteRoute
    }
    '/admin/contests/$contestId/': {
      id: '/admin/contests/$contestId/'
      path: '/contests/$contestId'
      fullPath: '/admin/contests/$contestId/'
      preLoaderRoute: typeof AdminContestsContestIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contests/$contestId/edit': {
      id: '/admin/contests/$contestId/edit'
      path: '/contests/$contestId/edit'
      fullPath: '/admin/contests/$contestId/edit'
      preLoaderRoute: typeof AdminContestsContestIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contests/$contestId/problems/create': {
      id: '/admin/contests/$contestId/problems/create'
      path: '/contests/$contestId/problems/create'
      fullPath: '/admin/contests/$contestId/problems/create'
      preLoaderRoute: typeof AdminContestsContestIdProblemsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contests/$contestId/problems/$problemId/edit': {
      id: '/admin/contests/$contestId/problems/$problemId/edit'
      path: '/contests/$contestId/problems/$problemId/edit'
      fullPath: '/admin/contests/$contestId/problems/$problemId/edit'
      preLoaderRoute: typeof AdminContestsContestIdProblemsProblemIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface ContestCodeRouteRouteChildren {
  ContestCodeIndexRoute: typeof ContestCodeIndexRoute
  ContestCodeProblemProblemIdRoute: typeof ContestCodeProblemProblemIdRoute
}

const ContestCodeRouteRouteChildren: ContestCodeRouteRouteChildren = {
  ContestCodeIndexRoute: ContestCodeIndexRoute,
  ContestCodeProblemProblemIdRoute: ContestCodeProblemProblemIdRoute,
}

const ContestCodeRouteRouteWithChildren =
  ContestCodeRouteRoute._addFileChildren(ContestCodeRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContestsCreateRoute: typeof AdminContestsCreateRoute
  AdminContestsContestIdEditRoute: typeof AdminContestsContestIdEditRoute
  AdminContestsContestIdIndexRoute: typeof AdminContestsContestIdIndexRoute
  AdminContestsContestIdProblemsCreateRoute: typeof AdminContestsContestIdProblemsCreateRoute
  AdminContestsContestIdProblemsProblemIdEditRoute: typeof AdminContestsContestIdProblemsProblemIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContestsCreateRoute: AdminContestsCreateRoute,
  AdminContestsContestIdEditRoute: AdminContestsContestIdEditRoute,
  AdminContestsContestIdIndexRoute: AdminContestsContestIdIndexRoute,
  AdminContestsContestIdProblemsCreateRoute:
    AdminContestsContestIdProblemsCreateRoute,
  AdminContestsContestIdProblemsProblemIdEditRoute:
    AdminContestsContestIdProblemsProblemIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContestCodeRouteRoute: ContestCodeRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
